version: "3.9"

services:
  spark-master:
    container_name: spark-master
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"   # Spark Master UI
      - "7077:7077"   # Spark submit
    networks:
      - spark-net
    volumes:
      - ../spark-app:/opt/spark-apps

  spark-worker-1:
    container_name: spark-worker-1
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"   # Spark Worker UI
    networks:
      - spark-net
    volumes:
      - ../spark-app:/opt/spark-apps

networks:
  spark-net:
